### ISSUE TITLE
not working on Linux

### ISSUE THREAD

**Issue by gvsurenderreddy** [sean-nicholas/remote-screen-client#11]
Hello sir
I cannot login from Mac to Linux and Windows to Linux but from Linux to Mac and Linux to Windows is possible.I think its due to Virtual IP i have on Linux

Also there is a way to give full support using your software thanks

**Comment by sean-nicholas** [comment]
Hey @gvsurenderreddy 
I'm sorry. I didn't saw your issue until now. Something strange with githubs notifications.

Using my Windows VM, I could connect easily to my linux host.

What do you mean with "Virtual IP"?
Are there any errors in the console?

**Comment by gvsurenderreddy** [comment]
sir its working takes longtime to Load but its a very good work.Sir full remote control app is possible please

**Comment by sean-nicholas** [comment]
full remote is beyond the scope of this project. Maybe you want to checkout this electron based project. Seems like it does what you are requesting: https://electronjs.org/apps/thismypc

**Comment by gvsurenderreddy** [comment]
Thank you so much for you help.SO kind of your sir.I cannot say in words how much it helps me thanks again

**Comment by sean-nicholas** [comment]
Glad I cloud help :)
